board_ohm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import handler404, handler500

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('create/', include('feed.urls')),
    path('update/', include('feed.urls')),
    path('delete/', include('feed.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('feed.urls'), name='feed-urls'),
]

# Add media files to urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers
handler404 = 'board_ohm.views.handler404'
handler500 = 'board_ohm.views.handler500'

feed/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('post_create/', views.AddPost.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostRead.as_view(), name='post_detail'),
    path(
        '<slug:slug>/update/',
        views.PostUpdate.as_view(), name='post_update'),
    path(
        '<slug:slug>/delete/',
        views.PostDelete.as_view(),
        name='post_delete'),
]

handler404 = 'board_ohm.views.handler404'
handler500 = 'board_ohm.views.handler500'

feed/models.py
from django.db import models
from django.contrib.auth.models import User

# Constant to hold the genre choices of game genre
GENRES = [
    ("camp", "Campaign"),
    ("card", "Card Game"),
    ("class", "Classic"),
    ("dex", "Dexterity"),
    ("draft", "Drafting"),
    ("edu", "Educational"),
    ("party", "Party"),
    ("puz", "Puzzle"),
    ("rpg", "Role-Playing Game"),
    ("strat", "Strategy"),
    ("war", "Wargame"),
    ("oth", "Other")
]

# Constant to hold the player count choices of game genre
PLAYER_COUNT = [
    ("any", "Any"),
    ("one_to_two", "1-2 Players"),
    ("one_to_three", "1-3 Players"),
    ("one_to_four", "1-4 Players"),
    ("one_to_five", "1-5 Players"),
    ("one_to_six", "1-6 Players"),
    ("one_to_eight", "1-8 Players"),
    ("two_to_four", "2-4 Players"),
    ("two_to_five", "2-5 Players"),
    ("two_to_six", "2-6 Players"),
    ("two_to_eight", "2-8 Players"),
    ("two_to_fifteen", "2-15 Players"),
    ("three_to_four", "3-4 Players"),
    ("three_to_five", "3-5 Players"),
    ("three_to_six", "3-6 Players"),
    ("three_to_eight", "3-8 Players"),
    ("three_to_fifteen", "3-15 Players"),
    ("oth", "Other")
]

# Constant to hold the age range choices of game genre
AGE_RANGE = [
    ("all", "All ages"),
    ("four_plus", "4 +"),
    ("five_plus", "5 +"),
    ("six_plus", "6 +"),
    ("seven_plus", "7 +"),
    ("eight_plus", "8 +"),
    ("ten_plus", "10 +"),
    ("twelve_plus", "12 +"),
    ("thirteen_plus", "13 +"),
    ("fourteen_plus", "14 +"),
    ("fifteen_pus", "15 +"),
    ("eigtheen_plus", "18 +"),
    ("oth", "Other")
]

# Constant to hold the play time choices of game genre
PLAY_TIME = [
    ("under_one", "10-30mins"),
    ("hour_to_two", "1-2 hours"),
    ("two_to_four", "2-4 hours"),
    ("over_four", "4 + hours"),
    ("rest_of", "The rest of your life"),
    ("oth", "Other")
]

# Constant to hold the experience choices of game genre
EXPERIENCE = [
    (1, "Casual"),
    (2, "Medium"),
    (3, "Not Suitable for Beginners"),
    (3, "Hardcore"),
    (4, "Friendship Ender")
]

# Constant to hold the price range choices of game genre
PRICE_RANGE = [
    (1, "$"),
    (2, "$$"),
    (3, "$$$"),
    (4, "$$$$"),
]

# Constant to hold the rating choices of game genre
RATING = [
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
]


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_posts')
    content = models.TextField(max_length=3000)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    genre = models.CharField(max_length=20, choices=GENRES, default="camp")
    number_of_players = models.CharField(
        max_length=100, choices=PLAYER_COUNT, default="one_to_four")
    age_range = models.CharField(
        max_length=20, choices=AGE_RANGE, default="four_plus")
    play_time = models.CharField(
        max_length=20, choices=PLAY_TIME, default="under_one")
    experience = models.IntegerField(choices=EXPERIENCE, default=1)
    price_range = models.IntegerField(choices=PRICE_RANGE, default=1)
    rating = models.IntegerField(choices=RATING, default=1)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"{self.title} | written by {self.author}"

feed/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    '''Form to create a new post'''
    class Meta:
        model = Post
        # add image field to form
        fields = ('title', 'content', 'image',
                  'genre', 'number_of_players', 'age_range',
                  'play_time', 'experience', 'price_range',
                  'rating', )
        labels = {
            'title': 'Title',
            'content': 'Content',
            'image': 'Image (If no image is selected, a default image will be used)',  # noqa
            'genre': 'Genre',
            'number_of_players': 'Number of Players',
            'age_range': 'Age Range',
            'play_time': 'Play Time',
            'experience': 'Experience',
            'price_range': 'Price Range',
            'rating': 'Rating',
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'genre': forms.Select(attrs={'class': 'form-control'}),
            'number_of_players': forms.Select(attrs={'class': 'form-control'}),
            'age_range': forms.Select(attrs={'class': 'form-control'}),
            'play_time': forms.Select(attrs={'class': 'form-control'}),
            'experience': forms.Select(attrs={'class': 'form-control'}),
            'price_range': forms.Select(attrs={'class': 'form-control'}),
            'rating': forms.Select(attrs={'class': 'form-control'}),
        }

feed/views.py
from typing import Any
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from .models import Post
from .forms import PostForm

# Create your views here.


class PostList(generic.ListView):
    ''' List all posts '''

    queryset = Post.objects.all()
    template_name = "feed/index.html"
    paginate_by = 8


class AddPost(View):
    '''Add a new post'''

    def get(self, request: Any) -> Any:
        '''Render the form'''
        form = PostForm()
        return render(request, "feed/post_create.html", {"form": form})

    def post(self, request: Any) -> Any:
        '''Create a new post'''
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(post.title)
            post.image = request.FILES.get("image")
            post.save()
            messages.add_message(
                    request, messages.SUCCESS, "Post created successfully")
            return redirect("home")
        else:
            messages.add_message(
                    request, messages.ERROR, "Post creation failed")
            return render(request, "feed/post_create.html", {"form": form})


class PostRead(generic.DetailView):
    '''Read a post'''

    model = Post
    template_name = "feed/post_read.html"


class PostUpdate(generic.UpdateView):
    '''Update a post'''

    model = Post
    template_name = "feed/post_update.html"
    form_class = PostForm
    success_url = "/"

    def check_user(self, request):
        '''Check if user is the author of the post'''
        post = get_object_or_404(Post, slug=self.kwargs.get("slug"))
        if request.user == post.author:
            return True
        else:
            return False

    def update_post(self, request):
        '''Update the post'''
        form = self.form_class(
            request.POST, request.FILES, instance=self.get_object())
        if form.is_valid():
            form.save()
            return True
        else:
            return False


class PostDelete(generic.DeleteView):
    '''Delete a post'''

    model = Post
    template_name = "feed/post_delete.html"
    success_url = "/"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Post deleted successfully")
        return super().delete(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        messages.error(self.request, "Post deletion failed")
        return super().post(request, *args, **kwargs)

feed/templates/feed/index.html
{% extends "base.html" %} {% block content %} {% load static %}

<!-- index.html content starts here -->
<div class="container-fluid p-4 mt-4">
  <div class="row">
    <div class="col-12 my-5 text-center">
      <h1>Welcome to Board-Ohm</h1>
      <h5>Keeping things zen at the table</h5>
      <div class="mt-3 p-3 text-center">
        <img class="image-fluid rounded"
          src="{% static 'images/logo-2.png' %}"
          alt="banner"
          style="max-width: 100%; height: auto">
      </div>
      <hr>
      {% if user.is_authenticated %}
      <div class="mx-3 mt-5 text-center">
        <a href="{% url 'post_create' %}" class="btn btn-outline-secondary btn-md text-light">
          <i class="fa-regular fa-plus light"></i> Add Post
        </a>
      </div>
      {% endif %}
      <div class="post-container row d-flex my-3">
        {% for post in post_list %}
        <div class="card post col-12 col-md-6 col-lg-3 my-5 text-center">
          <a href="{% url 'post_detail' post.slug %}" {% if post.image %}>
            <img src="{{ post.image.url }}"
              class="card-image img-fluid border border-white"
              alt="{{post.title}}"
              style="height: 300px">
            {% else %} >
            <img
              src="{% static 'images/default.jpg' %}"
              class="img-fluid rounded p-3"
              alt="{{post.title}}"
              style="height: 350px">
            {% endif %}
          </a>
          <div class="card-body row text-center">
            <a href="{% url 'post_detail' post.slug %}" class="link-light">
              <h3 class="card-title">
                {{ post.title }} <br>
                <span class="fs-5">written by {{ post.author }}</span>
              </h3>
            </a>
            <hr>
            <p class="card-text fs-6 col-6">
              <i class="fa-solid fa-dice"></i> {{ post.get_genre_display }}
              <br>
              <i class="fa-solid fa-clock"></i>
              {{ post.get_play_time_display }} <br>
              <i class="fa-solid fa-people-group"></i>
              {{ post.get_number_of_players_display }} <br>
            </p>
            <p class="card-text fs-6 col-6">
              Age: {{ post.get_age_range_display }} <br>
              Experience: {{ post.get_experience_display }} <br>
              Cost: {{ post.get_price_range_display }} <br>
            </p>
            <hr>
            <p class="card-text fs-6 col-12">
              Rating: {{ post.get_rating_display }} /5
            </p>
          </div>
          {% if user.is_authenticated and user == post.author or user.is_superuser %}
          <div class="row">
            <div class="col-6 text-end">
              <a href="{% url 'post_update' post.slug %}"
                class="btn btn-sm btn-outline-info text-light">
                <i class="fa-solid fa-pencil"></i>
              </a>
            </div>
            <div class="col-6 text-start">
              <a href="{% url 'post_delete' post.slug %}"
                class="btn btn-sm btn-outline-danger text-light">
                <i class="fa-solid fa-trash"></i>
              </a>
            </div>
          </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="mb-4">
            <a href="?page={{ page_obj.previous_page_number }}"
              class="page-link btn text-light">
              <i class="fa-solid fa-arrow-left"></i> PREV
            </a>
          </li>
          {% endif %} {% if page_obj.has_next %}
          <li class="mb-4">
            <a href="?page={{ page_obj.next_page_number }}"
              class="page-link btn text-light">
              NEXT <i class="fa-solid fa-arrow-right"></i>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

feed/templates/feed/post_create.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}


<div class="container p-3 my-5 bg-dark-subtle">
  <div class="row m-3 center">
  {% if user.is_authenticated %}
    <div class="col-12">
      <h1 class="text-center">Create a new post</h1>
    </div>
  </div>
  <div class="form-container row d-flex">
    <div class="col-12 col-md-8 m-4">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form|crispy }}
        <div class="text-center">
          <a href="{{request.META.HTTP_REFERER|escape}}"
            class="btn btn-secondary">
            Back
          </a>
          <button class="btn btn-primary" type="submit">Post</button>
        </div>
      </form>
    </div>
  </div>
  {% else %}
  <div class="row m-3 center">
    <div class="col-12">
      <h1 class="text-center">You must be logged in to create a post</h1>
    </div>
  </div>
  {% endif %}
</div>
 {% endblock %}

feed/templates/feed/post_delete.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %} 
{% if user.is_authenticated and user == post.author or user.is_superuser %}
<div class="container p-3 mt-5 bg-dark-subtle text-center">
  <div class="row m-3">
    <div class="col-12">
      <h1 class="text-center">Are you sure?</h1>
    </div>
  </div>
  <div class="row m-3 d-flex">
    <div class="form-group">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form|crispy }}
        <div class="text-center">
          <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-primary">
            Back
          </a>
          <button class="btn btn-danger" type="submit">Delete</button>
        </div>
      </form>
    </div>
  </div>
  {% else %}
  <div class="container p-3 bg-dark-subtle my-5">
    <div class="row m-3 center">
      <div class="col-12 my-5">
        <h3 class="text-center">You must be logged in and the owner of this post to delete it</h3>
      </div>
    </div>
    {% endif %} 
  </div>
{% endblock %}

feed/templates/feed/post_read.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div class="p-4 mt-5 text-center justify-content-center">
  {% if user.is_authenticated and user == post.author or user.is_superuser %}
  <div class="row">
    <div class="col-12 text-end">
      <a href="{% url 'post_update' post.slug %}" class="btn btn-sm btn-info text-light">
        <i class="fa-solid fa-pencil"></i>
      </a>
      <a href="{% url 'post_delete' post.slug %}" class="btn btn-sm btn-danger text-light">
        <i class="fa-solid fa-trash"></i>
      </a>
    </div>
  </div>
  {% endif %}
  <div class="text-center image-container align-items-center">
    <h2 class="text-center p-3"><u>{{ post.title }}</u></h2>
    {% if post.image %}
    <img src="{{ post.image.url }}" class="img-fluid rounded border border-white" alt="{{post.title}}">
    {% else %}
    <img src="{% static 'images/default.jpg' %}" class="img-fluid rounded border border-white" alt="{{post.title}}">
    {% endif %}
  </div>
  <div class="row border-bottom text-center lh-1 p-3">
    <div class="game-info-read col text-end">
      <p class="fs-6">
        <i class="fa-solid fa-dice"></i> {{post.get_genre_display}}
      </p>
      <p class="fs-6">
        <i class="fa-solid fa-clock"></i>
        {{post.get_play_time_display}}
      </p>
      <p class="fs-6">
        <i class="fa-solid fa-people-group"></i>
        {{post.get_number_of_players_display}}
      </p>
    </div>
    <div class="game-info-read col text-start">
      <p class="fs-6">Ages: {{ post.get_age_range_display }}</p>
      <p class="fs-6">Experience: {{ post.get_experience_display }}</p>
      <p class="fs-6">Cost: {{ post.get_price_range_display }}</p>
    </div>
    <p class="fs-6 rating">Rating: {{ post.get_rating_display }}/ 5</p>
  </div>
  <div class="text-block text-center p-2 mb-5 fs-4 justify-content-center">
    {{ post.content|safe|linebreaks }}
  </div>
</div>
{% endblock content %}

feed/templates/feed/post_update.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %} 
{% if user.is_authenticated and user == post.author or user.is_superuser %}
<div class="container p-4 mb-5 bg-dark-subtle">
  <div class="row mt-5 center">
    <div class="col-12 my-3">
      <h1 class="text-center">Update Post</h1>
    </div>
    <hr>
  </div>
  <div class="row mb-5 d-flex">
    <div class="form-group">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form|crispy }}
        <div class="text-center">
          <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-primary">Back</a>
          <button class="btn btn-success" type="submit">Post</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% else %}
<div class="container p-3 bg-dark-subtle my-5">
    <div class="row m-3 center">
      <div class="col-12 my-5">
        <h3 class="text-center">You must be logged in and the owner of this post to update it</h3>
      </div>
    </div>
  {% endif %} 
  {% endblock %}
</div>